TIME_FORCUS: 2
TIME_SKIP: 20
QUEUE_ENTRY_LIMIT_MIN: 15
NotifyAPI: http://localhost:1234/updated
Delay4CAP: 20
Port: 18080
#NameFile: < path to >iot/darknet-deps/data/coco.names 
#CfgFile: < path to > iot/darknet-deps/cfg/yolov4-tiny.cfg
#WeightFile: < path to > iot/darknet-deps/data/yolov4-tiny.weights
Threshold: 0.6
#Src: rtsp://admin:admin@192.168.1.3:554/cam/realmonitor?channel=4&subtype=1
#CorrectRate: 0.9
