name: CMake

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Run the build process with Docker
      uses: addnab/docker-run-action@v3
      with:
          image: longkl/iot:latest
          options: -v ${{ github.workspace }}:${{ github.workspace }}
          run: |
            cmake -B/home/runner/work/iot/iot/unittests/build -S /home/runner/work/iot/iot/unittests/
            cmake --build /home/runner/work/iot/iot/libs/services/unittests/build
            cd /home/runner/work/iot/iot/unittests/build && make test
            cmake -B/home/runner/work/iot/iot/build -S /home/runner/work/iot/iot/
            cmake --build /home/runner/work/iot/iot/build | grep 'Linking CXX executable iot'
